from quad_controller_rl.agents.policy_search import RandomPolicySearch
from quad_controller_rl.agents.base_agent import BaseAgent
from quad_controller_rl.agents.DDPG_Agent import DDPGAgent
from quad_controller_rl.agents.DQN_Agent import DQNAgent
